
interface ParsedFragment {
  funcId: string;
  args: string[];
}

// Function aliases
const ALIASES: Record<string, string> = {
  'location': 'Z26570', 'located in': 'Z26570',
  'is a': 'Z26039', 'instance of': 'Z26039',
  'kind of': 'Z26095', 'subclass of': 'Z26095',
  'role': 'Z28016', 'is the x of': 'Z28016',
  'describe': 'Z29591', 'adjective class': 'Z29591',
  'class of class': 'Z27173',
  'class with adj': 'Z29743',
  'superlative': 'Z27243',
  'spo': 'Z26955',
  'are': 'Z26627', 'plural class': 'Z26627',
  'album': 'Z28803',
  'sunset': 'Z30000',
  'begins': 'Z31405',
  'auto article': 'Z29822',
};

const REVERSE_ALIASES: Record<string, string> = {};
for (const [alias, zid] of Object.entries(ALIASES)) {
  if (!REVERSE_ALIASES[zid]) REVERSE_ALIASES[zid] = alias;
}

// State
const labelCache: Record<string, string> = {};
let currentQid = '';
let renderTimeout: ReturnType<typeof setTimeout> | null = null;

// DOM
const qidInput = document.getElementById('qid-input') as HTMLInputElement;
const btnWikidata = document.getElementById('btn-wikidata') as HTMLButtonElement;
const btnAbstract = document.getElementById('btn-abstract') as HTMLButtonElement;
const btnPush = document.getElementById('btn-push') as HTMLButtonElement;
const editorEl = document.getElementById('editor') as HTMLTextAreaElement;
const previewEl = document.getElementById('preview') as HTMLDivElement;
const statusEl = document.getElementById('status') as HTMLSpanElement;
const infoLeft = document.getElementById('info-left') as HTMLSpanElement;

// --- Pull from Wikidata (uses generate_wikitext.py) ---

btnWikidata.addEventListener('click', pullFromWikidata);
qidInput.addEventListener('keydown', (e) => { if (e.key === 'Enter') pullFromWikidata(); });

async function pullFromWikidata(): Promise<void> {
  const qid = normalizeQid();
  if (!qid) return;

  statusEl.textContent = 'Generating from Wikidata...';
  try {
    const wikitext = await window.api.generateWikitext(qid);
    editorEl.value = wikitext;
    statusEl.textContent = `${qid} - pulled from Wikidata`;
    infoLeft.textContent = 'Generated by generate_wikitext.py';
    btnPush.disabled = false;
    renderPreview();
  } catch (e) {
    statusEl.textContent = `Error: ${(e as Error).message}`;
  }
}

// --- Pull from Abstract Wikipedia ---

btnAbstract.addEventListener('click', pullFromAbstract);

async function pullFromAbstract(): Promise<void> {
  const qid = normalizeQid();
  if (!qid) return;

  statusEl.textContent = 'Fetching from Abstract Wikipedia...';
  try {
    const wikitext = await window.api.convertArticle(qid);
    editorEl.value = wikitext;
    statusEl.textContent = `${qid} - pulled from Abstract Wikipedia`;
    infoLeft.textContent = 'Converted by convert_article.py';
    btnPush.disabled = false;
    renderPreview();
  } catch (e) {
    statusEl.textContent = `Error: ${(e as Error).message}`;
  }
}

// --- Push to Abstract Wikipedia (uses edit_from_qid.py) ---

btnPush.addEventListener('click', async () => {
  const qid = normalizeQid();
  if (!qid) return;

  btnPush.disabled = true;
  statusEl.textContent = 'Pushing to Abstract Wikipedia (browser will open)...';
  try {
    const output = await window.api.pushArticle(qid, editorEl.value);
    if (output.includes('SUCCESS')) {
      statusEl.textContent = `${qid} - published!`;
    } else if (output.includes('ERROR')) {
      statusEl.textContent = `${qid} - error during push`;
      console.error(output);
    } else {
      statusEl.textContent = `${qid} - push finished`;
    }
  } catch (e) {
    const msg = (e as Error).message;
    statusEl.textContent = `Push error: ${msg.slice(0, 100)}`;
    console.error('Push error:', msg);
  }
  btnPush.disabled = false;
});

// --- Preview rendering ---

editorEl.addEventListener('input', () => {
  if (renderTimeout) clearTimeout(renderTimeout);
  renderTimeout = setTimeout(renderPreview, 300);
});

async function renderPreview(): Promise<void> {
  const text = editorEl.value;
  const fragments = parseTemplates(text);

  if (fragments.length === 0) {
    previewEl.innerHTML = '<span class="placeholder">No fragments to preview.</span>';
    return;
  }

  const needed = new Set<string>();
  for (const frag of fragments) {
    for (const arg of frag.args) {
      if (/^Q\d+$/.test(arg) && !labelCache[arg]) needed.add(arg);
    }
  }

  if (needed.size > 0) {
    previewEl.innerHTML = '<span class="placeholder">Resolving labels...</span>';
    const labels = await window.api.fetchLabels([...needed]);
    Object.assign(labelCache, labels);
  }

  previewEl.innerHTML = fragments.map(f =>
    `<div class="sentence">${renderSentence(f)}</div>`
  ).join('');
}

function parseTemplates(text: string): ParsedFragment[] {
  const fragments: ParsedFragment[] = [];
  const pattern = /\{\{(.+?)\}\}/gs;
  let match;
  while ((match = pattern.exec(text)) !== null) {
    const parts = match[1].trim().split('|').map(s => s.trim());
    if (parts.length === 0) continue;
    const funcId = ALIASES[parts[0].toLowerCase()] || parts[0];
    fragments.push({ funcId, args: parts.slice(1) });
  }
  return fragments;
}

function qLink(qid: string): string {
  const label = labelCache[qid] || qid;
  return `<a class="label" href="https://www.wikidata.org/wiki/${qid}" title="${qid}">${label}</a>`;
}

function resolveArg(a: string): string {
  if (a === '$subject') return qLink(currentQid);
  if (a === '$lang') return '<em>language</em>';
  if (/^Q\d+$/.test(a)) return qLink(a);
  return a;
}

function renderSentence(frag: ParsedFragment): string {
  const a = frag.args.map(resolveArg);
  switch (frag.funcId) {
    case 'Z26570': return `${a[0]} is a ${a[1]} in ${a[2]}.`;
    case 'Z26039': return `${a[0]} is a ${a[1]}.`;
    case 'Z26095': return `A ${a[0]} is a ${a[1]}.`;
    case 'Z28016': return `${a[0]} is the ${a[1]} of ${a[2]}.`;
    case 'Z26955': return `${a[1]} is ${a[0]} of ${a[2]}.`;
    case 'Z29591': return `${a[0]} is a ${a[1]} ${a[2]}.`;
    case 'Z26627': return `${a[0]} are ${a[1]}.`;
    case 'Z27243': return `${a[0]} is the ${a[1]} ${a[2]} in ${a[3]}.`;
    case 'Z27173': return `${a[0]} is ${a[1]} ${a[2]}.`;
    case 'Z29743': return `A ${a[0]} is a ${a[1]} ${a[2]}.`;
    default: return a.join(' ');
  }
}

function normalizeQid(): string {
  let qid = qidInput.value.trim().toUpperCase();
  if (!qid) return '';
  if (!qid.startsWith('Q')) qid = 'Q' + qid;
  qidInput.value = qid;
  currentQid = qid;
  return qid;
}
