
interface ParsedFragment {
  funcId: string;
  args: string[];
}

// Function aliases
const ALIASES: Record<string, string> = {
  'location': 'Z26570', 'located in': 'Z26570',
  'is a': 'Z26039', 'instance of': 'Z26039',
  'kind of': 'Z26095', 'subclass of': 'Z26095',
  'role': 'Z28016', 'is the x of': 'Z28016',
  'describe': 'Z29591', 'adjective class': 'Z29591',
  'class of class': 'Z27173',
  'class with adj': 'Z29743',
  'superlative': 'Z27243',
  'spo': 'Z26955',
  'are': 'Z26627', 'plural class': 'Z26627',
  'album': 'Z28803',
  'sunset': 'Z30000',
  'begins': 'Z31405',
  'auto article': 'Z29822',
  'comparative measurement': 'Z32229',
};

const REVERSE_ALIASES: Record<string, string> = {};
for (const [alias, zid] of Object.entries(ALIASES)) {
  if (!REVERSE_ALIASES[zid]) REVERSE_ALIASES[zid] = alias;
}

// State
const labelCache: Record<string, string> = {};
let currentQid = '';
let renderTimeout: ReturnType<typeof setTimeout> | null = null;
let hasCredentials = false;
let restoringRevId: string | null = null;

// DOM
const qidInput = document.getElementById('qid-input') as HTMLInputElement;
const btnWikidata = document.getElementById('btn-wikidata') as HTMLButtonElement;
const btnAbstract = document.getElementById('btn-abstract') as HTMLButtonElement;
const btnPush = document.getElementById('btn-push') as HTMLButtonElement;
const btnHistory = document.getElementById('btn-history') as HTMLButtonElement;
const btnLogin = document.getElementById('btn-login') as HTMLButtonElement;
const editorEl = document.getElementById('editor') as HTMLTextAreaElement;
const previewEl = document.getElementById('preview') as HTMLDivElement;
const statusEl = document.getElementById('status') as HTMLSpanElement;
const infoLeft = document.getElementById('info-left') as HTMLSpanElement;
const summaryBar = document.getElementById('summary-bar') as HTMLDivElement;
const editSummaryInput = document.getElementById('edit-summary') as HTMLInputElement;

// History view DOM
const historyView = document.getElementById('history-view') as HTMLDivElement;
const historyTitle = document.getElementById('history-title') as HTMLHeadingElement;
const historyList = document.getElementById('history-list') as HTMLDivElement;
const btnHistoryBack = document.getElementById('btn-history-back') as HTMLButtonElement;

// Login overlay elements
const loginOverlay = document.getElementById('login-overlay') as HTMLDivElement;
const loginUsername = document.getElementById('login-username') as HTMLInputElement;
const loginMainPassword = document.getElementById('login-main-password') as HTMLInputElement;
const loginSave = document.getElementById('login-save') as HTMLButtonElement;
const loginCancel = document.getElementById('login-cancel') as HTMLButtonElement;
const loginStatus = document.getElementById('login-status') as HTMLDivElement;

// --- Pull from Wikidata (uses generate_wikitext.py) ---

btnWikidata.addEventListener('click', pullFromWikidata);
qidInput.addEventListener('keydown', (e) => { if (e.key === 'Enter') pullFromWikidata(); });

async function pullFromWikidata(): Promise<void> {
  const qid = normalizeQid();
  if (!qid) return;

  statusEl.textContent = 'Generating from Wikidata...';
  try {
    const wikitext = await window.api.generateWikitext(qid);
    editorEl.value = wikitext;
    restoringRevId = null;
    statusEl.textContent = `${qid} - pulled from Wikidata`;
    infoLeft.textContent = 'Generated by generate_wikitext.py';
    btnPush.disabled = false;
    btnHistory.disabled = false;
    summaryBar.style.display = 'flex';
    renderPreview();
  } catch (e) {
    statusEl.textContent = `Error: ${(e as Error).message}`;
  }
}

// --- Pull from Abstract Wikipedia ---

btnAbstract.addEventListener('click', pullFromAbstract);

async function pullFromAbstract(): Promise<void> {
  const qid = normalizeQid();
  if (!qid) return;

  statusEl.textContent = 'Fetching from Abstract Wikipedia...';
  try {
    const wikitext = await window.api.convertArticle(qid);
    editorEl.value = wikitext;
    restoringRevId = null;
    statusEl.textContent = `${qid} - pulled from Abstract Wikipedia`;
    infoLeft.textContent = 'Converted by convert_article.py';
    btnPush.disabled = false;
    btnHistory.disabled = false;
    summaryBar.style.display = 'flex';
    renderPreview();
  } catch (e) {
    statusEl.textContent = `Error: ${(e as Error).message}`;
  }
}

// --- Push to Abstract Wikipedia (uses edit_from_qid.py) ---

btnPush.addEventListener('click', async () => {
  const qid = normalizeQid();
  if (!qid) return;

  btnPush.disabled = true;
  if (restoringRevId) {
    statusEl.textContent = `Restoring ${qid} to revision ${restoringRevId} (browser will open)...`;
  } else {
    statusEl.textContent = 'Pushing to Abstract Wikipedia (browser will open)...';
  }
  try {
    const summary = editSummaryInput.value.trim() || undefined;
    const output = await window.api.pushArticle(qid, editorEl.value, restoringRevId || undefined, summary);
    if (output.includes('SUCCESS')) {
      if (restoringRevId) {
        statusEl.textContent = `${qid} - restored to revision ${restoringRevId}!`;
      } else {
        statusEl.textContent = `${qid} - published!`;
      }
    } else if (output.includes('ERROR')) {
      statusEl.textContent = `${qid} - error during push`;
      console.error(output);
    } else {
      statusEl.textContent = `${qid} - push finished`;
    }
  } catch (e) {
    const msg = (e as Error).message;
    statusEl.textContent = `Push error: ${msg.slice(0, 100)}`;
    console.error('Push error:', msg);
  }
  restoringRevId = null;
  btnPush.disabled = false;
});

// --- Preview rendering ---

editorEl.addEventListener('input', () => {
  if (renderTimeout) clearTimeout(renderTimeout);
  renderTimeout = setTimeout(renderPreview, 300);
});

// Sync scroll between editor and preview
editorEl.addEventListener('scroll', () => {
  previewEl.scrollTop = editorEl.scrollTop;
});
previewEl.addEventListener('scroll', () => {
  editorEl.scrollTop = previewEl.scrollTop;
});

async function renderPreview(): Promise<void> {
  const text = editorEl.value;
  const lines = text.split('\n');

  // Collect all QIDs that need labels (from templates and section headers)
  const allFragments = parseTemplates(text);
  const needed = new Set<string>();
  for (const frag of allFragments) {
    for (const arg of frag.args) {
      if (/^Q\d+$/.test(arg) && !labelCache[arg]) needed.add(arg);
    }
  }
  const sectionHeaderPattern = /^==\s*(Q\d+)\s*==$/gm;
  let shMatch;
  while ((shMatch = sectionHeaderPattern.exec(text)) !== null) {
    if (!labelCache[shMatch[1]]) needed.add(shMatch[1]);
  }

  if (needed.size > 0) {
    previewEl.innerHTML = '<span class="placeholder">Resolving labels...</span>';
    const labels = await window.api.fetchLabels([...needed]);
    Object.assign(labelCache, labels);
  }

  // Render line-by-line so each preview line aligns with each textarea line
  let sectionNumber = 0;
  const html = lines.map(line => {
    const trimmed = line.trim();
    // {{p}} paragraph marker renders as a visual break
    if (/^\{\{\s*p\s*\}\}$/i.test(trimmed)) {
      return '<div class="sentence paragraph-break">&nbsp;</div>';
    }
    // ==...== section header
    const sectionMatch = /^==\s*(.+?)\s*==$/.exec(trimmed);
    if (sectionMatch) {
      const content = sectionMatch[1];
      if (/^Q\d+$/.test(content)) {
        // Valid QID: show label
        const label = labelCache[content] || content;
        return `<div class="sentence section-header"><h2>${label}</h2></div>`;
      } else {
        // Non-QID: show as auto-numbered
        sectionNumber++;
        return `<div class="sentence section-header"><h2>${sectionNumber} <em>(${content})</em></h2></div>`;
      }
    }
    const tmplMatch = /^\{\{(.+?)\}\}$/.exec(trimmed);
    if (tmplMatch) {
      const parts = tmplMatch[1].trim().split('|').map(s => s.trim());
      const funcId = ALIASES[parts[0].toLowerCase()] || parts[0];
      const frag: ParsedFragment = { funcId, args: parts.slice(1) };
      return `<div class="sentence">${renderSentence(frag)}</div>`;
    }
    // Non-template lines render as empty lines to maintain alignment
    return '<div class="sentence">&nbsp;</div>';
  }).join('');

  previewEl.innerHTML = html || '<span class="placeholder">No fragments to preview.</span>';
}

function parseTemplates(text: string): ParsedFragment[] {
  const fragments: ParsedFragment[] = [];
  const pattern = /\{\{(.+?)\}\}/gs;
  let match;
  while ((match = pattern.exec(text)) !== null) {
    const parts = match[1].trim().split('|').map(s => s.trim());
    if (parts.length === 0) continue;
    const funcId = ALIASES[parts[0].toLowerCase()] || parts[0];
    fragments.push({ funcId, args: parts.slice(1) });
  }
  return fragments;
}

function qLink(qid: string): string {
  const label = labelCache[qid] || qid;
  return `<a class="label" href="https://www.wikidata.org/wiki/${qid}" title="${qid}">${label}</a>`;
}

function resolveArg(a: string): string {
  if (a === 'SUBJECT') return qLink(currentQid);
  if (a === '$lang') return '<em>language</em>';
  if (/^Q\d+$/.test(a)) return qLink(a);
  return a;
}

function formatNumber(raw: string): string {
  if (!raw) return '?';
  if (raw.includes('/')) {
    const [n, d] = raw.split('/');
    return n.replace(/\B(?=(\d{3})+(?!\d))/g, ',') + '/' +
           d.replace(/\B(?=(\d{3})+(?!\d))/g, ',');
  }
  return raw.replace(/\B(?=(\d{3})+(?!\d))/g, ',');
}

function renderSentence(frag: ParsedFragment): string {
  const a = frag.args.map(resolveArg);
  switch (frag.funcId) {
    case 'Z26570': return `${a[0]} is a ${a[1]} in ${a[2]}.`;
    case 'Z26039': return `${a[0]} is a ${a[1]}.`;
    case 'Z26095': return `A ${a[0]} is a ${a[1]}.`;
    case 'Z28016': return `${a[0]} is the ${a[1]} of ${a[2]}.`;
    case 'Z26955': return `${a[1]} is ${a[0]} of ${a[2]}.`;
    case 'Z29591': return `${a[0]} is a ${a[1]} ${a[2]}.`;
    case 'Z26627': return `${a[0]} are ${a[1]}.`;
    case 'Z27243': return `${a[0]} is the ${a[1]} ${a[2]} in ${a[3]}.`;
    case 'Z27173': return `${a[0]} is ${a[1]} ${a[2]}.`;
    case 'Z29743': return `A ${a[0]} is a ${a[1]} ${a[2]}.`;
    case 'Z32229': return `${a[0]} has a ${a[2]} ${formatNumber(a[3])} times that of ${a[1]}.`;
    default: return a.join(' ');
  }
}

function normalizeQid(): string {
  let qid = qidInput.value.trim().toUpperCase();
  if (!qid) return '';
  if (!qid.startsWith('Q')) qid = 'Q' + qid;
  qidInput.value = qid;
  currentQid = qid;
  return qid;
}

// --- History view ---

function showEditorView(): void {
  historyView.style.display = 'none';
  previewEl.style.display = '';
  (document.querySelector('.info') as HTMLElement).style.display = '';
  editorEl.style.display = '';
}

function showHistoryView(): void {
  historyView.style.display = '';
  previewEl.style.display = 'none';
  (document.querySelector('.info') as HTMLElement).style.display = 'none';
  editorEl.style.display = 'none';
}

btnHistory.addEventListener('click', async () => {
  const qid = normalizeQid();
  if (!qid) return;

  showHistoryView();
  historyTitle.textContent = `Revision History — ${qid}`;
  historyList.innerHTML = '<span class="placeholder">Loading revisions...</span>';

  try {
    const revisions = await window.api.fetchRevisions(qid);
    if (revisions.length === 0) {
      historyList.innerHTML = '<span class="placeholder">No revisions found. The article may not exist yet.</span>';
      return;
    }

    historyList.innerHTML = '';
    revisions.forEach((rev, index) => {
      const item = document.createElement('div');
      item.className = 'history-item';

      const date = new Date(rev.timestamp);
      const dateStr = date.toLocaleString();

      const infoDiv = document.createElement('div');
      infoDiv.className = 'rev-info';
      infoDiv.innerHTML = `
        <div>
          <span class="rev-id">${rev.revid}</span>
          <span class="rev-date">${dateStr}</span>
          <span class="rev-size">(${rev.size} bytes)</span>
        </div>
        <div class="rev-user">${rev.user}</div>
        ${rev.comment ? `<div class="rev-comment">${rev.comment}</div>` : ''}
      `;
      item.appendChild(infoDiv);

      if (index === 0 && revisions.length > 1) {
        // Latest revision — offer "Undo" which restores to the parent (second revision)
        const undoBtn = document.createElement('button');
        undoBtn.className = 'btn-undo';
        undoBtn.textContent = 'Undo';
        undoBtn.addEventListener('click', () => restoreRevision(qid, revisions[1].revid.toString()));
        item.appendChild(undoBtn);
      }

      if (index > 0) {
        // Older revisions — offer "Restore"
        const restoreBtn = document.createElement('button');
        restoreBtn.className = 'btn-restore';
        restoreBtn.textContent = 'Restore';
        restoreBtn.addEventListener('click', () => restoreRevision(qid, rev.revid.toString()));
        item.appendChild(restoreBtn);
      }

      historyList.appendChild(item);
    });
  } catch (e) {
    historyList.innerHTML = `<span class="placeholder">Error loading revisions: ${(e as Error).message}</span>`;
  }
});

async function restoreRevision(qid: string, revId: string): Promise<void> {
  statusEl.textContent = `Loading revision ${revId}...`;

  try {
    const wikitext = await window.api.convertArticleRevision(qid, revId);
    editorEl.value = wikitext;
    restoringRevId = revId;
    statusEl.textContent = `${qid} - loaded revision ${revId} (click Push to restore)`;
    infoLeft.textContent = `Restoring to revision ${revId}`;
    btnPush.disabled = false;
    summaryBar.style.display = 'flex';
    showEditorView();
    renderPreview();
  } catch (e) {
    statusEl.textContent = `Error loading revision: ${(e as Error).message}`;
  }
}

btnHistoryBack.addEventListener('click', showEditorView);

// --- Login ---

async function checkCredentials(): Promise<void> {
  const creds = await window.api.getCredentials();
  if (creds && creds.mainPassword) {
    hasCredentials = true;
    btnLogin.textContent = 'Logged in';
    btnLogin.classList.add('logged-in');
  } else {
    hasCredentials = false;
    btnLogin.textContent = 'Login';
    btnLogin.classList.remove('logged-in');
  }
}

btnLogin.addEventListener('click', async () => {
  loginOverlay.classList.add('visible');
  loginStatus.textContent = '';
  loginStatus.className = 'login-status';

  const creds = await window.api.getCredentials();
  if (creds) {
    loginUsername.value = creds.username;
    loginMainPassword.value = creds.mainPassword;
  }
});

loginCancel.addEventListener('click', () => {
  loginOverlay.classList.remove('visible');
});

loginOverlay.addEventListener('click', (e) => {
  if (e.target === loginOverlay) loginOverlay.classList.remove('visible');
});

loginSave.addEventListener('click', async () => {
  const username = loginUsername.value.trim();
  const mainPassword = loginMainPassword.value.trim();

  if (!username || !mainPassword) {
    loginStatus.textContent = 'Username and password are required.';
    loginStatus.className = 'login-status err';
    return;
  }

  const ok = await window.api.saveCredentials({ username, mainPassword });
  if (ok) {
    loginStatus.textContent = 'Credentials saved.';
    loginStatus.className = 'login-status ok';
    await checkCredentials();
    setTimeout(() => loginOverlay.classList.remove('visible'), 800);
  } else {
    loginStatus.textContent = 'Failed to save credentials.';
    loginStatus.className = 'login-status err';
  }
});

// Check on startup
checkCredentials();
